### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by rmauritsson** [rmauritsson/micro_facebook#1]
This is the review about Devise and omniauth by Team Power Rangers

**Comment by RoyNyaga** [comment]
You can create a controller that will inherit from the devise default registrations controller to have more control over users' information.

**Comment by KerronKing** [comment]
You can also make edits directly to the controllers that devise generates. Just check out the "Configuring controllers" section on the devise documentation page for further info. Otherwise, just remember to set your routes for any pages you may utilise.

**Comment by rmauritsson** [comment]
Thanks Guys
I have implemented the advise given
